[tool:pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

[playwright]
headed = true
slow_mo = 1000
args = ["--start-maximized"]

[pytest]
addopts =
    --alluredir=allure-results
    --clean-alluredir

log_format = [%(asctime)s)[%(name)s][%(levelname)s] %(message)s
log_level = INFO
markers =
    positive: marks tests as positive scenarios
    negative: marks tests as negative scenarios
    edge: marks tests as edge cases
    bug: marks tests as known bugs
